# Generated by Django 3.2.9 on 2022-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
