# Generated by Django 3.2.9 on 2022-03-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220321_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
