# Generated by Django 4.0.2 on 2022-03-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
